version: '3.8'

services:
  postgres: 
    image: postgres:latest
    container_name: postgres
    ports:
      - 5858:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: '0.1'